# Generated by Django 5.2.1 on 2025-05-26 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searchhistory',
            options={'ordering': ['-last_search']},
        ),
    ]
